## **1)—NumPy’s ndarray – Incredible Power at Your Fingertips!**

### **Import Statements**

We follow the standard convention of importing NumPy as `np`. Additional libraries are prepared for plotting and image handling later in the notebook.

```python
import numpy as np
import matplotlib.pyplot as plt
from scipy import misc
from PIL import Image
```

---

### **The ndarray: Core Concept**

The most important object in NumPy is the **ndarray**.

An `ndarray` is a **homogeneous n-dimensional array**:

* **Homogeneous** means all elements share the same data type (for example, all floating-point numbers).
* **n-dimensional** means the array can represent data in one dimension (a vector), two dimensions (a matrix), or many dimensions stacked together.

This structure is what enables NumPy’s speed and efficiency.

---

### **1-Dimensional Arrays (Vectors)**

A 1-dimensional ndarray represents a vector.

```python
my_array = np.array([1.1, 9.2, 8.1, 4.7])
```

Check its shape:

```python
my_array.shape
```

```text
(4,)
```

Access an element by index:

```python
my_array[2]
```

```text
8.1
```

Check the number of dimensions:

```python
my_array.ndim
```

```text
1
```

---

### **Key Attributes**

* `shape`: returns a tuple describing the length of each axis
* `ndim`: returns the total number of dimensions

These attributes are essential for understanding and navigating ndarrays.

---

### **2-Dimensional Arrays (Matrices)**

A 2-dimensional ndarray represents a matrix with rows and columns.

```python
array_2d = np.array([
    [1, 2, 3, 9],
    [5, 6, 7, 8]
])
```

Inspect dimensions and structure:

```python
print(f"array_2d has {array_2d.ndim} dimensions")
print(f"Its shape is {array_2d.shape}")
print(f"It has {array_2d.shape[0]} rows and {array_2d.shape[1]} columns")
print(array_2d)
```

```text
array_2d has 2 dimensions
Its shape is (2, 4)
It has 2 rows and 4 columns
[[1 2 3 9]
 [5 6 7 8]]
```

---

### **Indexing 2-Dimensional Arrays**

Access a single value by providing an index for each dimension:

```python
array_2d[1, 2]
```

```text
7
```

Access an entire row using slicing:

```python
array_2d[0, :]
```

```text
array([1, 2, 3, 9])
```

---

### **N-Dimensional Arrays (Tensors)**

Arrays with three or more dimensions are commonly referred to as **tensors**. This is the same concept used in machine learning libraries such as TensorFlow.

```python
mystery_array = np.array([
    [[0, 1, 2, 3],
     [4, 5, 6, 7]],

    [[7, 86, 6, 98],
     [5, 1, 0, 4]],

    [[5, 36, 32, 48],
     [97, 0, 27, 18]]
])
```

Check dimensions and shape:

```python
print(f"We have {mystery_array.ndim} dimensions")
print(f"The shape is {mystery_array.shape}")
```

```text
We have 3 dimensions
The shape is (3, 2, 4)
```

This means:

* 3 elements along axis 0
* 2 elements along axis 1
* 4 elements along axis 2

---

### **Indexing Higher-Dimensional Arrays**

Access a single value by specifying one index per axis:

```python
mystery_array[2, 1, 3]
```

```text
18
```

Retrieve a 1-dimensional vector from the last axis:

```python
mystery_array[2, 1, :]
```

```text
array([97,  0, 27, 18])
```

Retrieve all first elements along the third axis:

```python
mystery_array[:, :, 0]
```

```text
array([[ 0,  4],
       [ 7,  5],
       [ 5, 97]])
```

---

### **Important Takeaways**

* Each pair of square brackets corresponds to one axis
* The number of indices must match the number of dimensions
* The colon operator `:` selects all values along an axis
* Higher-dimensional arrays require practice to visualise and index correctly

Mastering `ndarray`, along with `shape`, `ndim`, indexing, and slicing, is foundational for all advanced NumPy operations.
