## **3)—Broadcasting, Scalars and Matrix Multiplication**

### **Linear Algebra with Vectors**

NumPy is designed for numerical computation and follows the rules of mathematics and linear algebra. When working with NumPy arrays, operations on vectors, matrices, and tensors behave as a mathematician would expect.

Consider two vectors:

```python
v1 = np.array([4, 5, 2, 7])
v2 = np.array([2, 1, 3, 3])
```

Adding them performs **element-wise addition**:

```python
v1 + v2
```

Result:

```python
array([6, 6, 5, 10])
```

This is fundamentally different from Python lists:

```python
list1 = [4, 5, 2, 7]
list2 = [2, 1, 3, 3]

list1 + list2
```

Result:

```python
[4, 5, 2, 7, 2, 1, 3, 3]
```

List addition concatenates, while NumPy performs numerical operations.

Multiplication of NumPy vectors is also element-wise:

```python
v1 * v2
```

Result:

```python
array([8, 5, 6, 21])
```

This operation is not supported for Python lists.

---

### **Broadcasting**

Often, you will want to perform operations between an array and a single number (a **scalar**). NumPy automatically expands the scalar to match the shape of the array. This process is called **broadcasting**.

Example with a 1-dimensional array:

```python
v = np.array([5, 10, 6, 17, 20])
v * 2
```

Each element is multiplied by the scalar.

Broadcasting also works with higher-dimensional arrays:

```python
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])
```

Adding a scalar:

```python
array_2d + 10
```

Result:

```python
array([[11, 12, 13, 14],
       [15, 16, 17, 18]])
```

Multiplying by a scalar:

```python
array_2d * 5
```

Result:

```python
array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])
```

Broadcasting works across multiple dimensions as long as the shapes are compatible. NumPy automatically expands dimensions of size 1 to match the larger array.

---

### **Broadcasting Rules (Conceptual)**

* Dimensions are compared from right to left
* Dimensions must be equal or one of them must be 1
* The result has the maximum size along each axis

This applies to 1D, 2D, and higher-dimensional arrays.

---

### **Matrix Multiplication**

When multiplying two arrays that represent matrices, NumPy follows the rules of **linear algebra**, not element-wise multiplication.

Example matrices:

```python
a1 = np.array([[1, 3],
               [0, 1],
               [6, 2],
               [9, 7]])

b1 = np.array([[4, 1, 3],
               [5, 8, 5]])
```

To perform matrix multiplication, use either:

```python
np.matmul(a1, b1)
```

or the `@` operator:

```python
a1 @ b1
```

Result:

```python
array([[19, 25, 18],
       [ 5,  8,  5],
       [34, 22, 28],
       [71, 65, 62]])
```

The resulting matrix has:

* 4 rows (from `a1`)
* 3 columns (from `b1`)

---

### **Understanding the Math Behind Matrix Multiplication**

Each element in the result is computed as a dot product of a row and a column.

Examples:

```text
c12 = (1 * 1) + (3 * 8) = 25
c33 = (6 * 3) + (2 * 5) = 28
```

This confirms that NumPy’s output follows standard matrix multiplication rules exactly.

---

### **Key Takeaways**

* NumPy performs element-wise operations by default
* Broadcasting allows scalars and smaller arrays to operate on larger arrays
* Broadcasting works across multiple dimensions when shapes are compatible
* Matrix multiplication must use `@` or `np.matmul()`
* NumPy strictly follows linear algebra rules for matrix operations
